// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoUGs4AT4_XFovLEn95i4nDvXYkayEHNY',
    appId: '1:465787257125:web:1d3658f17a1c5180731acc',
    messagingSenderId: '465787257125',
    projectId: 'fatec-manha-app-cafe',
    authDomain: 'fatec-manha-app-cafe.firebaseapp.com',
    storageBucket: 'fatec-manha-app-cafe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfPaG1BrPlvOezZugWh1ydTQeWUOl4d-o',
    appId: '1:465787257125:android:648c61d7d651452a731acc',
    messagingSenderId: '465787257125',
    projectId: 'fatec-manha-app-cafe',
    storageBucket: 'fatec-manha-app-cafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ULd7iDsXIF7VEe8EI3ZU1xxTiCHbICE',
    appId: '1:465787257125:ios:bd9030baa5420ba4731acc',
    messagingSenderId: '465787257125',
    projectId: 'fatec-manha-app-cafe',
    storageBucket: 'fatec-manha-app-cafe.appspot.com',
    iosClientId: '465787257125-aeu29548q9h325jplprrkruivq0c701v.apps.googleusercontent.com',
    iosBundleId: 'com.example.app07LojaCafe',
  );
}
